image: openjdk:8-jdk

variables:
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  # Install needed utilities
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  # Install latest CLI tools to $ANDROID_HOME
  - export ANDROID_HOME="${PWD}/android-home"
  - install -d $ANDROID_HOME
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - popd
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/

  # Finish SDK manager setup
  - sdkmanager --version
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true

cache:
  paths:
    - .m2/
    - .gradle/

stages:
  - build
  - lint
  - test
  - package

.check:
  stage: lint
  script:
    - ./gradlew --console=plain check

assembleDebug:
  stage: build
  script:
    - ./gradlew --console=plain assembleDebug

debugTests:
  stage: test
  script:
    - ./gradlew --console=plain testDebug

bundleRelease:
  stage: package
  only:
    - /^release\/.*$/
    - /^build\/.*$/
  script:
    - ./gradlew -PkeyStorePassword="$KEYSTORE_RELEASE_PASSWORD" --console=plain bundleRelease
  artifacts:
    paths:
      - app/build/outputs/
      - app-wear/build/outputs/
